### ISSUE TITLE
Prefabs

### ISSUE THREAD

**Issue by damibran** [GiiGaTeam/GiiGaEngine#94]
Это особый тип ассетов, позволяющий хранить весь GameObject со всеми компонентами и значениями свойств. Префаб выступает в роли шаблона для создания экземпляров хранимого объекта в сцене. Любые изменения в префабе немедленно отражаются и на всех его экземплярах, при этом вы можете переопределять компоненты и настройки для каждого экземпляра в отдельности.

# Наш дизайн

Префаб это PrefabAsset -- json с корневым GameObject, его компоненты и дети.

{
    "RootGameObject" : "UUID",
    "GameObjects" :
    [
        "Regular Game Object Json",
        "Regular Game Object Json"
        ....
        "Regular Game Object Json"
    ]
}

## Как будет выглядеть использование Prefab в сцене

Для удобства построения дизайна рассмотрим сценарии использования.

- Опираясь на текущую реализацию #13. 

### Сериализация сцены (сохранение)

Как только мы встречаем GameObject, у которого свойство Prefab : PrefabAsset != Null, вместо обычного процесса сериализации GO (запись свойств GO, его компонентов и детей), мы создаем JSON объект следующей структуры:

```javascript
{
    "Prefab" : "{AssetHandle.Json}",
    "Modifications": 
    [
        {
            "Target" : "UUID",
            "Modification" : "{}"
        }
    ],
    "AddedGameObjects" : ["Regular game Object define"]
}
``` 

**Как составить список модификаций?**

# Анализ файлов scene и prefab в unity:

[Scene.txt](https://github.com/user-attachments/files/17756583/Scene.txt)
[Prefab.txt](https://github.com/user-attachments/files/17756587/Prefab.txt)

У каждого элемента сериализации (GameObject/Component) имеется видимо уникальный (в рамках файла) fileID.
```yml
--- !u!1 &5755123991398664843
GameObject:
```

Удивительно, но также у каждого элемента (даже компонента) есть следующие поля:
```
m_PrefabInstance: {fileID: 0}
m_PrefabAsset: {fileID: 0}
```
Зачем они нужны пока не понимаю, случаев, когда id не 0 не видел.

## Scene

В файле записан PrefabInstance имеющий список модификаций m_Modifications, записывающий изменения некоторого параметра элемента с индексом fileID (из файла prefab).
```yml
- target: {fileID: 5755123991398664843, guid: 9abb2082779f38d4f966e57eef0b2a53, type: 3}
      propertyPath: m_Name
      value: GameObjectMyPrefab
      objectReference: {fileID: 0}
```
также у PrefabInstance имеется следующий список:
```yml
m_RemovedComponents: []
m_RemovedGameObjects: []
m_AddedGameObjects: []
m_AddedComponents: []
```
и сам файл оригинала префаба
`m_SourcePrefab: {fileID: 100100000, guid: 9abb2082779f38d4f966e57eef0b2a53, type: 3}`

## Prefab

В файле также записаны GameObject'ы и Component'ы.
Если в скриптах есть ссылки на GO или Comp, то они также записываются при помощи fileID:
```yml
MonoBehaviour:
  ...
  m_EditorClassIdentifier: 
  transfrom1: {fileID: 8168364855295709959}
  go2: {fileID: 1053527154274960376}
```

# Если в скрипте в качестве параметра типа GameObject передать Prefab

Установится ссылка fileID корневого GameObject

## Как отличить реальный GameObject от такого prefab

Судя [по](https://discussions.unity.com/t/how-to-tell-if-a-gameobject-is-an-instance-or-a-prefab/105642) у GameObject есть поле принадлежности к сцене. У префаба нет принадлежности.

# Вопросы

- [ ] Как различать prefab от обычных GameObject в сцене (после загрузки в память)? _и надо ли_ (точно нужно в editor режиме)
